# Workflow for testing and publishing of the snapshot checkout artifact

name: Publish snapshot artifact
on:
  push:
    branches:
      - "develop"

jobs:
  test-checkout:
    name: Test checkout module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run Checkout unit-tests
        run: ./gradlew testCheckout

  test-examples:
    name: Test example apps
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Test examples on Browserstack
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew testExampleAppsOnAppAutomate

  publish:
    needs: test-examples
    name: Publish snapshot artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Publish checkout artifact
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publishCheckoutSnapshotVersion